package hebmorph

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/json"
	"fmt"
	"math"
)

// frequencies.json.gz ranks every lemma by how common it is in a corpus of
// Modern Hebrew, generated by ./internal/gen/frequencies. It is what lets
// readingsOf answer with the sense a reader is most likely to have met first,
// rather than in hspell's order, which has nothing to do with usage.
//
// It is gzipped JSON for the same reason the gloss table is (see transGz), and
// smaller still: a rank is a position, so the file is just the lemmas' word
// indexes, most frequent first.
//
//go:embed data/frequencies.json.gz
var freqGz []byte

// loadFrequencies fills d.ranks from the embedded table.
//
// The file lists lemmas in rank order; this inverts it into a rank per word
// index, so a reading's rank is an array index rather than a map hit. Two
// bytes per dictionary word is a small fraction of what the dictionary itself
// takes, and the lookup is on the path of every reading.
func (d *dictionary) loadFrequencies() error {
	zr, err := gzip.NewReader(bytes.NewReader(freqGz))
	if err != nil {
		return fmt.Errorf("open embedded frequencies: %w", err)
	}
	var lemmas []int32
	if err := json.NewDecoder(zr).Decode(&lemmas); err != nil {
		return fmt.Errorf("decode frequencies: %w", err)
	}
	// Ranks are held as uint16 on every reading, so the table has to fit.
	if len(lemmas) > math.MaxUint16 {
		return fmt.Errorf("frequency table ranks %d lemmas, more than a rank can hold (%d)", len(lemmas), math.MaxUint16)
	}

	d.ranks = make([]uint16, len(d.words))
	for i, lemma := range lemmas {
		if lemma < 0 || int(lemma) >= len(d.words) {
			return fmt.Errorf("frequency rank %d names word %d, which is outside the dictionary", i+1, lemma)
		}
		// Rank 1 is the most frequent lemma, so the zero value stays free to
		// mean "unranked".
		d.ranks[lemma] = uint16(i + 1)
	}
	return nil
}

// rankOf returns how common the reading's lemma is in Modern Hebrew, where 1
// is the most frequent lemma in the dictionary. It is 0 when the lemma is
// unranked, which sorts it last.
//
// Frequency is counted per lemma, so it tells apart readings with different
// lemmas — אביהו as "his father" from the name Avihu — but says nothing about
// two readings of one lemma, which share a rank.
func (d *dictionary) rankOf(wordIndex, stemIndex int32) uint16 {
	lemma, _ := d.lemmaOf(wordIndex, stemIndex)
	if lemma < 0 || int(lemma) >= len(d.ranks) {
		return 0
	}
	return d.ranks[lemma]
}
