package hebmorph

import (
	_ "embed"
	"fmt"
)

// lemmas.json.gz is the sense table, generated by ./internal/gen/lemmas: every
// distinct word the dictionary can mean, with its English and its Modern
// Hebrew frequency rank, plus the lemma each reading resolves to.
//
// A lemma is one distinct word, not one spelling. Hebrew writes no vowels, so
// unrelated words collide: את is the direct-object marker, the preposition
// "with", and the pronoun "you" — three lemmas sharing a spelling. Conversely
// one lemma answers for many words, since inflection does not change meaning.
//
// Which lemma a reading means is decided at build time and stored per reading,
// so nothing here has to work it out: the answer is an array index. That is
// worth the space, because the rule is not derivable from a reading alone —
// see the package comment on ./internal/gen/lemmas.
//
//go:embed data/lemmas.json.gz
var lemmasGz []byte

// lemma is one distinct word: a sense of a spelling.
type lemma struct {
	Word    int32    `json:"w"`              // index into dictionary.words: how it is spelled
	POS     string   `json:"pos"`            // part of speech, refining hspell's four
	English []string `json:"en"`             // most representative sense first
	Rank    uint16   `json:"rank,omitempty"` // 1 = most frequent; 0 = unranked
}

// lemmaFile mirrors blob.Lemmas, the on-disk shape.
type lemmaFile struct {
	Table []lemma   `json:"lemmas"`
	Of    [][]int32 `json:"of"`
}

// loadLemmas fills d.lemmas and d.lemmaOf from the embedded sense table.
func (d *dictionary) loadLemmas() error {
	var f lemmaFile
	if err := loadGzipJSON(lemmasGz, &f, "lemmas"); err != nil {
		return err
	}
	if len(f.Of) != len(d.readings) {
		return fmt.Errorf("lemmas: %d reading lists against the dictionary's %d", len(f.Of), len(d.readings))
	}
	for w, of := range f.Of {
		if len(of) != len(d.readings[w]) {
			return fmt.Errorf("lemmas: word %q has %d readings but %d lemmas",
				d.words[w], len(d.readings[w]), len(of))
		}
		for _, id := range of {
			if id < -1 || int(id) >= len(f.Table) {
				return fmt.Errorf("lemmas: word %q names lemma %d, which is out of range", d.words[w], id)
			}
		}
	}
	d.lemmas, d.lemmaOf = f.Table, f.Of
	return nil
}

// lemmaAt returns the lemma of a word's i'th reading, or nil when it has none.
func (d *dictionary) lemmaAt(wordIndex int32, i int) *lemma {
	if wordIndex < 0 || int(wordIndex) >= len(d.lemmaOf) {
		return nil
	}
	of := d.lemmaOf[wordIndex]
	if i < 0 || i >= len(of) || of[i] < 0 {
		return nil
	}
	return &d.lemmas[of[i]]
}
