package hebmorph

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/binary"
	"fmt"
	"io"
)

// translations.gz holds one English gloss set per (stem, part of speech),
// generated by ./internal/gen/translations. Only stems are listed — the
// 341,585 dictionary words collapse onto 20,917 of them, and inflection does
// not change meaning — so the table is keyed by the same word index that
// reading.stemIndex uses.
//
// Format (gzipped): a uvarint stem count, then for each stem in ascending
// index order: uvarint word index, uvarint group count, then per group one
// part-of-speech byte (dmask&dTypeMask), a uvarint gloss count, and that many
// (uvarint length + UTF-8 bytes) strings.
//
//go:embed data/translations.gz
var transGz []byte

// glossGroup is a stem's English translations in one part of speech. pos is
// stored as dmask&dTypeMask so a reading matches it by bitmask rather than by
// comparing part-of-speech names.
type glossGroup struct {
	pos     int32
	english []string
}

// loadGlosses fills d.glosses from the embedded translation table.
func (d *dictionary) loadGlosses() error {
	zr, err := gzip.NewReader(bytes.NewReader(transGz))
	if err != nil {
		return fmt.Errorf("open embedded translations: %w", err)
	}
	raw, err := io.ReadAll(zr)
	if err != nil {
		return fmt.Errorf("decompress translations: %w", err)
	}

	r := bytes.NewReader(raw)
	n64, err := binary.ReadUvarint(r)
	if err != nil {
		return fmt.Errorf("read stem count: %w", err)
	}
	n := int(n64)

	d.glosses = make(map[int32][]glossGroup, n)
	for i := 0; i < n; i++ {
		stemIdx, err := binary.ReadUvarint(r)
		if err != nil {
			return fmt.Errorf("stem %d index: %w", i, err)
		}
		if int(stemIdx) >= len(d.words) {
			return fmt.Errorf("stem %d index %d out of range", i, stemIdx)
		}
		ng, err := binary.ReadUvarint(r)
		if err != nil {
			return fmt.Errorf("stem %d group count: %w", i, err)
		}
		groups := make([]glossGroup, ng)
		for j := range groups {
			pos, err := r.ReadByte()
			if err != nil {
				return fmt.Errorf("stem %d group %d pos: %w", i, j, err)
			}
			ne, err := binary.ReadUvarint(r)
			if err != nil {
				return fmt.Errorf("stem %d group %d gloss count: %w", i, j, err)
			}
			english := make([]string, ne)
			for k := range english {
				glen, err := binary.ReadUvarint(r)
				if err != nil {
					return fmt.Errorf("stem %d group %d gloss %d length: %w", i, j, k, err)
				}
				b := make([]byte, glen)
				if _, err := io.ReadFull(r, b); err != nil {
					return fmt.Errorf("stem %d group %d gloss %d bytes: %w", i, j, k, err)
				}
				english[k] = string(b)
			}
			groups[j] = glossGroup{pos: int32(pos), english: english}
		}
		d.glosses[int32(stemIdx)] = groups
	}
	return nil
}

// glossesOf returns the stem's English translations in the part of speech the
// reading's dmask names, or nil when that pairing has no verified translation.
// The returned slice is shared and must not be modified.
func (d *dictionary) glossesOf(stemIndex int32, dmask int) []string {
	for _, g := range d.glosses[stemIndex] {
		if int(g.pos) == dmask&dTypeMask {
			return g.english
		}
	}
	return nil
}
