package hebmorph

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/json"
	"fmt"
)

// translations.json.gz holds one English gloss set per (lemma, part of
// speech), generated by ./internal/gen/translations. Inflection does not
// change meaning, so only lemmas are listed — 22,412 of them against 342k
// words — keyed by the same word index that reading.stemIndex uses.
//
// It is gzipped JSON, not the packed encoding data/hebrew.dict.gz uses: at a
// fourteenth the size, packing it saves 4% of bytes and 15ms of one-time
// decoding, which does not pay for a codec on both sides of the build.
//
//go:embed data/translations.json.gz
var transGz []byte

// glossGroup is a lemma's English translations in one part of speech. POS is
// stored as dmask&dTypeMask so a reading matches it by bitmask rather than by
// comparing part-of-speech names.
type glossGroup struct {
	POS int32 `json:"pos"`
	// Bucket marks a gloss keyed by the word itself rather than by a stem.
	// See dictionary.miscStem and glossesOf.
	Bucket  bool     `json:"bucket,omitempty"`
	English []string `json:"english"`
}

// loadGlosses fills d.glosses from the embedded translation table.
func (d *dictionary) loadGlosses() error {
	zr, err := gzip.NewReader(bytes.NewReader(transGz))
	if err != nil {
		return fmt.Errorf("open embedded translations: %w", err)
	}
	if err := json.NewDecoder(zr).Decode(&d.glosses); err != nil {
		return fmt.Errorf("decode translations: %w", err)
	}

	// Resolved once here so glossesOf compares indexes, not strings.
	d.miscStem = -1
	if i, ok := d.index["שונות"]; ok {
		d.miscStem = i
	}
	return nil
}

// glossesOf returns the English translations of the reading's lemma in the
// part of speech its dmask names, or nil when that pairing has no verified
// translation. The returned slice is shared and must not be modified.
//
// The lemma is normally the stem. But hspell has no stem for proper nouns,
// acronyms and particles: they all name the שונות bucket, so for those the
// word is its own lemma, and the bucket flag tells the two apart — אדם is
// "man, person" through its stem and "Adam" through the bucket, in the same
// part of speech, on the same word.
func (d *dictionary) glossesOf(wordIndex, stemIndex int32, dmask int) []string {
	lemma, bucket := stemIndex, stemIndex == d.miscStem
	if bucket {
		lemma = wordIndex
	}
	for _, g := range d.glosses[lemma] {
		if int(g.POS) == dmask&dTypeMask && g.Bucket == bucket {
			return g.English
		}
	}
	return nil
}
